language: python
cache:
  directories:
  - "/Library/Caches/Homebrew"
  - "$HOME/.cache/pip"
env:
  global:
  - COMMIT=${TRAVIS_COMMIT::8}
matrix:
  include:
  - os: linux
    python: 3.5
    env: DEPLOY_FILE=dist/release/AYAB*.tar.gz
  - os: osx
    language: generic
    env: DEPLOY_FILE=dist/release/AYAB*.dmg
  allow_failures:
  - os: osx
before_install:
- TAG=$(git describe --tags)
- echo $TAG > package_version
- cat package_version
- if [ "$TRAVIS_OS_NAME" == "osx"   ]; then mac-build/install.sh; fi
- if [ "$TRAVIS_OS_NAME" == "linux" ]; then linux-build/install.sh; fi
install: true
script:
- cd dist/release
- ls
- if [ "$TRAVIS_OS_NAME" == "osx"   ]; then mv AYAB.dmg AYAB-OSX-${TAG}.dmg; fi
- if [ "$TRAVIS_OS_NAME" == "linux" ]; then mv ayab*.tar.gz AYAB-Linux-${TAG}.tar.gz; fi
- ls
- cd ../..
before_cache:
- rm -f $HOME/.cache/pip/log/debug.log
