language: python
cache:
  directories:
  - "/Library/Caches/Homebrew"
  - "$HOME/.cache/pip"
env:
  global:
  - COMMIT=${TRAVIS_COMMIT::8}
  - secure: iEOOpeumhuWXGfnwSX1VGN/2OmECJdlACCWJV2eJ1J6EEDCzD6t0XYleoCB8nFJSITbeYHvuSGVrb3Fu2ccVXk1wMGaQpTtvRH5aurQGnJd9QarYG9HV1jDnlmnSqaflBN5i9gND7qmzyEK2jCF7l6VRJ3e8yTrtjICw4NJ7Ba02YVRtwecPu0igRmDMAUUi1Jv6hUohfqvB8d8yG8ps6akYa7hQGMTeUxcIWMrgl5VJP32HuKlqB84+0QE6F+GFf1YXZT3QrhVYO1V/BQl/eQ0zvku5g5+JtHHw5dhCz/H01sFKx3e5pOkcR6jehfzsIvdBwijSYeR747A+XB2PA7BIRX/l2Aaj7icqskJAdZCMwhSMCQiUefK4HuWXGwJbj3tXwzgN0eOISzHS6wjqOz7KTFIdakvGgJOLb9SZTdjVhR7A8gVD4iMKBZ9tgorMy8cTIJQ2lnvSjxA2NCetzsby52DB6Yl+vcD0bAQ2uO5aH3TlrPsiDT7DCnKiOOHFqOkSGRySqX60NUYVCZ75hUZLFTRIpqDYaIfCOe8TWhFLwGzLOBd0/uzsFaNwMP6AfVaNdGqbmtxLGflBCBAphIT65/XLCEOF5bNKGubNGI2QCiiQxtMt+YUb2PLS6NzI5XemTD5xtOmo/y3hlp5HFhplgiB98ciFLsZFfQHQeIU=
  - secure: YfP6LrmvF7oes/2zL4d5SBddor2QM+t2xBdQydCFv0MTnNikUlgNnIO/fit4GMSxaNaBEXKCD5SmcoGlQAQUdgLEQbyE81GbDK8ezfCEKrodyZH5s0IlvsZTHSNcqhwDyRwT3ppy3ICRRUlJVU5eExB/erTmbmF5r5icVjvkKK59QYlZbNTD1TReKerA44zL0sTdhYjaBcehJi8X5szW7mnJW+TCNnGezQxEeAj40XU5s8JMVSqKFnZ64k4qF58DIC5/V57nCIDLubqSnSGr+omwM9SiRWsaJ61sC1cEglkKksXjCQPHch2tPwLET6RLFy8JX6D1hMe+P+4D0+VmAQeLwAm4/9W3GgXD/FKriSj19A63Z/o3xmKtaRozPFxqYM47ZQVS3BnrrbbXCha1Jo7h3TjRudUrCyqcSp3BDvQbzhsteX3vVmva9oFOerosC7+bSx8bZ7N8jUxdWzNKQ+kfaHL3qdLeOem8ZLxziziPYaolP9i92h3PErC2p1PQroS8Vr/jmW41fkVuzONYpCed5AjB8CHJ7/q4FH0GtYdkiOQHdXHpv+n6HR2v4JWXgkfzq25F+A+8+ar40TRfJ8ag/Aqyf2foMSVNnAnx/3csa30QB5uZEy4SLovFOZlFk8MKU4GycmHjRnP3Wz/Kj+ZZ7+ei0RDbWddHwXQg+t4=
matrix:
  include:
  - os: linux
    python: 3.4
    env: DEPLOY_FILE=dist/release/AYAB*.tar.gz
  - os: osx
    language: generic
    env: DEPLOY_FILE=dist/release/AYAB*.dmg
  allow_failures:
  - os: osx
before_install:
- TAG=$(git describe --tags)
- echo $TAG > package_version
- cat package_version
- perl -i -pe "s/PACKAGE_VERSION/${TAG}/g" ayab/__init__.py
- perl -i -pe "s/PACKAGE_VERSION/${TAG}/g" ayab/ayab_about.ui
- pip install pyqt5
- pyuic5 ayab/ayab_about.ui -o ayab/ayab_about.py
- if [ "$TRAVIS_OS_NAME" == "osx"   ]; then mac-build/install.sh; fi
- if [ "$TRAVIS_OS_NAME" == "linux" ]; then linux-build/install.sh; fi
- if [ "$TRAVIS_OS_NAME" == "linux" ]; then pip install awscli && aws s3 rm s3://ayab-debug --recursive --region eu-central-1; fi
install: true
script:
- cd dist/release
- ls
- if [ "$TRAVIS_OS_NAME" == "osx"   ]; then mv AYAB.dmg AYAB-OSX-${TAG}.dmg; fi
- if [ "$TRAVIS_OS_NAME" == "linux" ]; then mv ayab*.tar.gz AYAB-Linux-${TAG}.tar.gz; fi
- ls
- cd ../..
before_cache:
- rm -f $HOME/.cache/pip/log/debug.log
deploy:
- provider: s3
  bucket: ayab-debug
  acl: public_read
  local_dir: dist/release
  overwrite: true
  skip_cleanup: true
  region: eu-central-1
  on:
    repo: AllYarnsAreBeautiful/ayab-desktop
    branch: python3
- provider: releases
  api_key:
    secure: PEEOBJp94cyGZgL5GjiGWeg9OXKv3cGmrSW8QiDmbHl4Go7oYvbk+ixXorT7L3/hZPcsjLzvIhZp3HLY5Xm2VPLNi9OWvggqtWlETgU6pOn24XlhujpMUm1e0JSYQwyL6CWmXxjDB5R1mzaVLj4dVeczBY+qDABmiUHTjPGJg3B9GezrM3lB/M5in3PkwmrC207IPEZi6uy8ZYFA/i290E2z3D/j4ITsHiKLLwUmWpZ1jP2JXtEvE6rPFv84/7310y7yNdCu8j+7E41n08phbPEhk3/hWcfDp8tR+Bb3SKZ70w2wpTPd7NxmVQ2iv0yzHDlKJmuaokxGTIDu/JcTYn2VBc9tzHB4nmYzeRDkbz6jl9kMTM/L2PzlPa5IdtNgm8v+veWo52fYFz65KC81vOJSYtC95S1j/ykZglmmfi0IcKOvl0zenXtgKaIKQ9p7of1ZUyKkXF1gfolZCLL1w69H7lCBpaBv37KxBixcCZLu5XDj7OU6BB3HwFLqFoAEEgCTjJNfEN7FOsg6PgGQARcNrNLqNV/R6VA9WNozNIdcGJbjVSquu/Z/VpmTmfasDRSAUrK80Za+NvFHiswJYadhjz1L6Qb8Xukf1UWwtxr3kFLvu69AcS3Tq4IHTIUxBdDIb3t8djgaSb0yg2jZ1EHxTL9RfLau3rhi9NOIhfg=
  file: "$DEPLOY_FILE"
  file_glob: true
  skip_cleanup: true
  overwrite: true
  on:
    tags: true
